# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcv4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class calc(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 611)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("* {\n"
"  box-sizing: border-box;\n"
"}\n"
"body {\n"
"  font-family: \"Open Sans\";\n"
"  line-height: 1.618em;\n"
"  background: #2c3e50;\n"
"}\n"
".wrapper {\n"
"  max-width: 65rem;\n"
"  width: 100%;\n"
"  margin: 2rem auto;\n"
"  padding: 5rem;\n"
"  text-align: center;\n"
"  background: #fff;\n"
"  border: 0.5rem solid #34495e;\n"
"}\n"
"hr {\n"
"  border: 0;\n"
"  border-bottom: 0.0625rem solid #bbb;\n"
"  margin: 3rem 0;\n"
"}\n"
"button {\n"
"  font-size: 2em;\n"
"  background: #3498db;\n"
"  color: #fff;\n"
"  border: 0.25rem solid #3498db;\n"
"  padding: 0.85em 0.75em;\n"
"  margin: 1rem;\n"
"  position: relative;\n"
"  z-index: 1;\n"
"  overflow: hidden;\n"
"}\n"
"button:hover {\n"
"  color: #3498db;\n"
"}\n"
"button::after {\n"
"  content: \"\";\n"
"  background: #ecf0f1;\n"
"  position: absolute;\n"
"  z-index: -1;\n"
"  padding: 0.85em 0.75em;\n"
"  display: block;\n"
"}\n"
"button[class^=\"slide\"]::after {\n"
"  transition: all 0.35s;\n"
"}\n"
"button[class^=\"slide\"]:hover::after {\n"
"  left: 0;\n"
"  right: 0;\n"
"  top: 0;\n"
"  bottom: 0;\n"
"  transition: all 0.35s;\n"
"}\n"
"button.slide_from_left::after {\n"
"  top: 0;\n"
"  bottom: 0;\n"
"  left: -100%;\n"
"  right: 100%;\n"
"}\n"
"button.slide_from_right::after {\n"
"  top: 0;\n"
"  bottom: 0;\n"
"  left: 100%;\n"
"  right: -100%;\n"
"}\n"
"button.slide_from_top::after {\n"
"  left: 0;\n"
"  right: 0;\n"
"  top: -100%;\n"
"  bottom: 100%;\n"
"}\n"
"button.slide_from_bottom::after {\n"
"  left: 0;\n"
"  right: 0;\n"
"  top: 100%;\n"
"  bottom: -100%;\n"
"}\n"
"button[class^=\"grow\"]::after {\n"
"  transition: all 0.3s ease;\n"
"}\n"
"button[class^=\"grow\"]:hover::after {\n"
"  transition: all 0.3s ease-out;\n"
"}\n"
"button.grow_box::after {\n"
"  left: 0;\n"
"  right: 0;\n"
"  top: 0;\n"
"  bottom: 0;\n"
"  transform: scale(0, 0);\n"
"}\n"
"button.grow_box:hover::after {\n"
"  transform: scale(1, 1);\n"
"}\n"
"button.grow_ellipse::after {\n"
"  border-radius: 50%;\n"
"  left: -50%;\n"
"  right: -50%;\n"
"  top: -150%;\n"
"  bottom: -150%;\n"
"  line-height: 8.34em;\n"
"  transform: scale(0, 0);\n"
"}\n"
"button.grow_ellipse:hover::after {\n"
"  transform: scale(1, 1);\n"
"}\n"
"button.grow_skew_forward::after {\n"
"  left: -20%;\n"
"  right: -20%;\n"
"  top: 0;\n"
"  bottom: 0;\n"
"  transform: skewX(-45deg) scale(0, 1);\n"
"}\n"
"button.grow_skew_forward:hover::after {\n"
"  transform: skewX(-45deg) scale(1, 1);\n"
"}\n"
"button.grow_skew_backward::after {\n"
"  left: -20%;\n"
"  right: -20%;\n"
"  top: 0;\n"
"  bottom: 0;\n"
"  transform: skewX(45deg) scale(0, 1);\n"
"}\n"
"button.grow_skew_backward:hover::after {\n"
"  transform: skewX(45deg) scale(1, 1);\n"
"}\n"
"button.grow_spin::after {\n"
"  left: 0;\n"
"  right: 0;\n"
"  top: 0;\n"
"  bottom: 0;\n"
"  transform: scale(0, 0) rotate(-180deg);\n"
"}\n"
"button.grow_spin:hover::after {\n"
"  transform: scale(1, 1) rotate(0deg);\n"
"}\n"
"")
        self.btn_clear = QtWidgets.QPushButton(Form)
        self.btn_clear.setGeometry(QtCore.QRect(370, 200, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 249, 179);")
        self.btn_clear.setObjectName("btn_clear")
        self.btn2 = QtWidgets.QPushButton(Form)
        self.btn2.setGeometry(QtCore.QRect(210, 200, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn2.setObjectName("btn2")
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(130, 200, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn1.setObjectName("btn1")
        self.btn3 = QtWidgets.QPushButton(Form)
        self.btn3.setGeometry(QtCore.QRect(290, 200, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);\n"
"")
        self.btn3.setObjectName("btn3")
        self.btn7 = QtWidgets.QPushButton(Form)
        self.btn7.setGeometry(QtCore.QRect(130, 370, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(Form)
        self.btn8.setGeometry(QtCore.QRect(210, 370, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(Form)
        self.btn9.setGeometry(QtCore.QRect(290, 370, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn9.setObjectName("btn9")
        self.btn6 = QtWidgets.QPushButton(Form)
        self.btn6.setGeometry(QtCore.QRect(290, 290, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn6.setObjectName("btn6")
        self.btn5 = QtWidgets.QPushButton(Form)
        self.btn5.setGeometry(QtCore.QRect(210, 290, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn5.setObjectName("btn5")
        self.btn4 = QtWidgets.QPushButton(Form)
        self.btn4.setGeometry(QtCore.QRect(130, 290, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn4.setObjectName("btn4")
        self.btn0 = QtWidgets.QPushButton(Form)
        self.btn0.setGeometry(QtCore.QRect(210, 450, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn0.setObjectName("btn0")
        self.btn_plus = QtWidgets.QPushButton(Form)
        self.btn_plus.setGeometry(QtCore.QRect(370, 290, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(Form)
        self.btn_minus.setGeometry(QtCore.QRect(370, 370, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_pow = QtWidgets.QPushButton(Form)
        self.btn_pow.setGeometry(QtCore.QRect(370, 450, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_pow.setFont(font)
        self.btn_pow.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn_pow.setObjectName("btn_pow")
        self.btn_div = QtWidgets.QPushButton(Form)
        self.btn_div.setGeometry(QtCore.QRect(30, 200, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn_div.setObjectName("btn_div")
        self.btn_mult = QtWidgets.QPushButton(Form)
        self.btn_mult.setGeometry(QtCore.QRect(30, 290, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_mult.setFont(font)
        self.btn_mult.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn_mult.setObjectName("btn_mult")
        self.btn_sqrt = QtWidgets.QPushButton(Form)
        self.btn_sqrt.setGeometry(QtCore.QRect(30, 370, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_sqrt.setFont(font)
        self.btn_sqrt.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.btn_dot = QtWidgets.QPushButton(Form)
        self.btn_dot.setGeometry(QtCore.QRect(30, 450, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(22)
        self.btn_dot.setFont(font)
        self.btn_dot.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.btn_dot.setObjectName("btn_dot")
        self.btn_eq = QtWidgets.QPushButton(Form)
        self.btn_eq.setGeometry(QtCore.QRect(30, 530, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(18)
        self.btn_eq.setFont(font)
        self.btn_eq.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(82, 255, 102);")
        self.btn_eq.setObjectName("btn_eq")
        self.table = QtWidgets.QLCDNumber(Form)
        self.table.setGeometry(QtCore.QRect(30, 20, 431, 171))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.table.setFont(font)
        self.table.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(217, 220, 207);")
        self.table.setObjectName("table")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(130, 450, 71, 71))
        self.widget.setStyleSheet("background-color: rgb(217, 220, 207);\n"
"border-radius:10px;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(290, 450, 71, 71))
        self.widget_2.setStyleSheet("background-color: rgb(217, 220, 207);\n"
"border-radius:10px;")
        self.widget_2.setObjectName("widget_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Калькулятор v2.0"))
        self.btn_clear.setText(_translate("Form", "C"))
        self.btn2.setText(_translate("Form", "2"))
        self.btn1.setText(_translate("Form", "1"))
        self.btn3.setText(_translate("Form", "3"))
        self.btn7.setText(_translate("Form", "7"))
        self.btn8.setText(_translate("Form", "8"))
        self.btn9.setText(_translate("Form", "9"))
        self.btn6.setText(_translate("Form", "6"))
        self.btn5.setText(_translate("Form", "5"))
        self.btn4.setText(_translate("Form", "4"))
        self.btn0.setText(_translate("Form", "0"))
        self.btn_plus.setText(_translate("Form", "+"))
        self.btn_minus.setText(_translate("Form", "-"))
        self.btn_pow.setText(_translate("Form", "^"))
        self.btn_div.setText(_translate("Form", "/"))
        self.btn_mult.setText(_translate("Form", "*"))
        self.btn_sqrt.setText(_translate("Form", "√"))
        self.btn_dot.setText(_translate("Form", "Помощь"))
        self.btn_eq.setText(_translate("Form", "="))