# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reader3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Reader(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 900)
        Form.setMinimumSize(QtCore.QSize(1200, 900))
        Form.setMaximumSize(QtCore.QSize(1200, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/button_blank_yellow_14988.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 850, 191, 41))
        self.pushButton.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(168, 168, 168);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 850, 191, 41))
        self.pushButton_2.setStyleSheet("border-radius:10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 850, 191, 41))
        self.pushButton_3.setStyleSheet("border-radius:10px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 1141, 811))
        self.label.setStyleSheet("border-radius:10px;\nbackground-color: rgb(168, 168, 168);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(660, 850, 461, 31))
        self.label_2.setStyleSheet("border-radius:10px;\nbackground-color: rgb(168, 168, 168);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ридер2"))
        self.pushButton.setText(_translate("Form", "Открыть картинку"))
        self.label_2.setText(_translate("Form", "Макс размер ∞"))

