# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ttts1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Pz(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1001, 640)
        Form.setMinimumSize(QtCore.QSize(1001, 640))
        Form.setMaximumSize(QtCore.QSize(1001, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/button_blank_green_14986.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(166, 166, 166);")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(40, 40, 931, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setCursorPosition(87)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 10, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 130, 931, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setCursorPosition(81)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 220, 931, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setCursorPosition(81)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 310, 931, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setCursorPosition(79)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 400, 931, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_5.setCursorPosition(96)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 490, 931, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_6.setCursorPosition(73)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 580, 931, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(225, 225, 225);")
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_7.setCursorPosition(66)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ридер видео"))
        self.lineEdit.setText(_translate("Form", "Привет, я разработчик этой программы хочу поведать тебе о том как же её изпользовать)xD"))
        self.label.setText(_translate("Form", "Пользовательская справка"))
        self.lineEdit_2.setText(_translate("Form", "1)Просмотр картинки: там вы можете открыть нужную вам картинку с расширинием .jpg"))
        self.lineEdit_3.setText(_translate("Form", "Любой другой вид картинкок на данный момент не может быть рассмотрен в программе!"))
        self.lineEdit_4.setText(_translate("Form", "2)Ридер файлов с расширением .txt: анологично первому, но файл должен быть .txt"))
        self.lineEdit_5.setText(_translate("Form", "В ином случае файл не откроется, также вы можете свободно редактировать текст из открытого файла"))
        self.lineEdit_6.setText(_translate("Form", "3)Калькулятор: создан для небольших расчётов, макс число для вывода 99999.\nОшибка в калькуляторе возможна с шансом в 0.1 процент.\nВ случае ошибки просим скинуть скрин на почту\nkitsorokin115@gmail.com"))
        self.lineEdit_7.setText(_translate("Form", "4)Ридер gif файлов, всё анологично 1 ридеру, но с расширением .gif"))