# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v3menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Menu(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(451, 600)
        Form.setMinimumSize(QtCore.QSize(451, 600))
        Form.setMaximumSize(QtCore.QSize(451, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(212, 237, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 411, 61))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(149, 255, 224);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 140, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(156, 255, 201);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 250, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(156, 255, 201);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 360, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(156, 255, 201);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 470, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(156, 255, 201);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 570, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(156, 255, 201);")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Меню"))
        self.label.setText(_translate("Form", "Добро пожаловать^_^:"))
        self.pushButton.setText(_translate("Form", "Просмотр  Картинки"))
        self.pushButton_2.setText(_translate("Form", "Чтение .txt "))
        self.pushButton_3.setText(_translate("Form", "Калькулятор"))
        self.pushButton_4.setText(_translate("Form", "Просмотр  gif"))
        self.pushButton_5.setText(_translate("Form", "?"))